name: Commissary
main: tech.ciaran.commissary.Main
version: 1.0-SNAPSHOT
api-version: 1.13
author: [Ciaran Baker, Ricardo R.]
softdepend: [PlaceholderAPI]
commands:
    commissary:
      description: Open the commissary menu.
    tickets:
      description: View your ticket balance.